export const UrlBase = "bookpages/"

export const CssFilenames = {
    'css': 'asciidoctor.css'
};

export const PostScript = `
    document.querySelector("body.article").addEventListener("click", doSomething, false);
    
    function doSomething(e) {
        var clickedItem = e.target.href;
        window.postMessage(clickedItem);
        e.preventDefault();
        return false;
    }`;


const PagesFilenames = {
    'about': 'about.html',
    'acetaminophen': 'acetaminophen.html',
    'adverse_drug_effects': 'adverse_drug_effects.html',
    'assessment_tools': 'assessment_tools.html',
    'before_calling_consult': 'before_calling_consult.html',
    'benzo_withdrawal': 'benzo_withdrawal.html',
    'cardiac_main': 'cardiac_main.html',
    'cardiology_ekg': 'cardiology_ekg.html',
    'cardiology_hlhs': 'cardiology_hlhs.html',
    'cardiology_hypertension': 'cardiology_hypertension.html',
    'chony_picu_main': 'chony_picu_main.html',
    'constipation_treatment': 'constipation_treatment.html',
    'cries_scale': 'cries_scale.html',
    'diazepam': 'diazepam.html',
    'disclaimer': 'disclaimer.html',
    'dka': 'dka.html',
    'drugs_basic_principles': 'drugs_basic_principles.html',
    'ed_section': 'ed_section.html',
    'emergency_med_acetaminophen_ingestion': 'emergency_med_acetaminophen_ingestion.html',
    'emergency_med_anaphylaxis': 'emergency_med_anaphylaxis.html',
    'emergency_med_asthma': 'emergency_med_asthma.html',
    'emergency_med_asthma_action_plan': 'emergency_med_asthma_action_plan.html',
    'emergency_med_cac_guidelines': 'emergency_med_cac_guidelines.html',
    'emergency_med_cac_toxicology_testing': 'emergency_med_cac_toxicology_testing.html',
    'emergency_med_croup': 'emergency_med_croup.html',
    'emergency_med_lp_competency': 'emergency_med_lp_competency.html',
    'emergency_med_oral_contrast': 'emergency_med_oral_contrast.html',
    'emergency_med_pain_control': 'emergency_med_pain_control.html',
    'emergency_med_procedural_sedation': 'emergency_med_procedural_sedation.html',
    'emergency_med_salter': 'emergency_med_salter.html',
    'emergency_med_splinting': 'emergency_med_splinting.html',
    'emergency_med_suspected_child_abuse': 'emergency_med_suspected_child_abuse.html',
    'emergency_med_suturing': 'emergency_med_suturing.html',
    'emergency_med_trauma': 'emergency_med_trauma.html',
    'endocrine_dka': 'endocrine_dka.html',
    'endocrine_endo_emergencies': 'endocrine_endo_emergencies.html',
    'endocrine_hypoglycemia': 'endocrine_hypoglycemia.html',
    'endocrine_insulin': 'endocrine_insulin.html',
    'endocrine_steroid': 'endocrine_steroid.html',
    'faces_revised': 'faces_revised.html',
    'gastritis': 'gastritis.html',
    'gi_liver_nutrition_gi_feeding': 'gi_liver_nutrition_gi_feeding.html',
    'gi_liver_nutrition_gi_nutrition': 'gi_liver_nutrition_gi_nutrition.html',
    'gi_liver_nutrition_tpn_fluids': 'gi_liver_nutrition_tpn_fluids.html',
    'heme_onc_bmt_onc_admit_discharge': 'heme_onc_bmt_onc_admit_discharge.html',
    'heme_onc_bmt_onc_blood_products': 'heme_onc_bmt_onc_blood_products.html',
    'heme_onc_bmt_onc_chemo': 'heme_onc_bmt_onc_chemo.html',
    'heme_onc_bmt_onc_common_dx': 'heme_onc_bmt_onc_common_dx.html',
    'heme_onc_bmt_onc_emerg': 'heme_onc_bmt_onc_emerg.html',
    'heme_onc_bmt_sickle_cell': 'heme_onc_bmt_sickle_cell.html',
    'heme_onc_bmt_sickle_cell_pain_crisis': 'heme_onc_bmt_sickle_cell_pain_crisis.html',
    'ouchapp_home': 'ouchapp_home.html',
    'icu_code_asystole_pea': 'icu_code_asystole_pea.html',
    'icu_code_blood_products': 'icu_code_blood_products.html',
    'icu_code_code_cab': 'icu_code_code_cab.html',
    'icu_code_cpr': 'icu_code_cpr.html',
    'icu_code_electrolyte_repletion': 'icu_code_electrolyte_repletion.html',
    'icu_code_hyperkalemia': 'icu_code_hyperkalemia.html',
    'icu_code_hypocalcemia': 'icu_code_hypocalcemia.html',
    'icu_code_hypokalemia': 'icu_code_hypokalemia.html',
    'icu_code_icu_code': 'icu_code_icu_code.html',
    'icu_code_icu_drips': 'icu_code_icu_drips.html',
    'icu_code_inotropic_agents': 'icu_code_inotropic_agents.html',
    'icu_code_pain_sedation_paralytics': 'icu_code_pain_sedation_paralytics.html',
    'icu_code_rapid_sequence_intubation': 'icu_code_rapid_sequence_intubation.html',
    'icu_code_svt': 'icu_code_svt.html',
    'icu_code_unstable_bradycardia': 'icu_code_unstable_bradycardia.html',
    'icu_code_vfib_pulseless_vt': 'icu_code_vfib_pulseless_vt.html',
    'icu_code_vt': 'icu_code_vt.html',
    'icu_section': 'icu_section.html',
    'infectious_disease_antibiotics': 'infectious_disease_antibiotics.html',
    'infectious_disease_fever_without_source1': 'infectious_disease_fever_without_source1.html',
    'infectious_disease_fever_without_source2': 'infectious_disease_fever_without_source2.html',
    'ketamine': 'ketamine.html',
    'ketorolac_post_op_cardiac': 'ketorolac_post_op_cardiac.html',
    'lorazepam_protocol': 'lorazepam_protocol.html',
    'main_section': 'main_section.html',
    'med_surg_11_main': 'med_surg_11_main.html',
    'med_surg_9_main': 'med_surg_9_main.html',
    'methadone': 'methadone.html',
    'methadone_protocol': 'methadone_protocol.html',
    'misc_ethanol_lock': 'misc_ethanol_lock.html',
    'misc_gt_ng_supplies': 'misc_gt_ng_supplies.html',
    'misc_heparin_lock_for_cvl': 'misc_heparin_lock_for_cvl.html',
    'nausea_treatment': 'nausea_treatment.html',
    'neonatal_gbs_mom': 'neonatal_gbs_mom.html',
    'neonatal_hepb': 'neonatal_hepb.html',
    'neonatal_hyperbili': 'neonatal_hyperbili.html',
    'neonatal_ivh': 'neonatal_ivh.html',
    'neonatal_nec': 'neonatal_nec.html',
    'neonatal_neonatal_ecmo_monitoring': 'neonatal_neonatal_ecmo_monitoring.html',
    'neonatal_nutrition': 'neonatal_nutrition.html',
    'neonatal_postnatal_glucose': 'neonatal_postnatal_glucose.html',
    'neonatal_resuscitation_2016_2017': 'neonatal_resuscitation_2016_2017.html',
    'neonatal_rop': 'neonatal_rop.html',
    'neonatal_torch': 'neonatal_torch.html',
    'neonatal_tpn_feeds': 'neonatal_tpn_feeds.html',
    'neonatal_ua_uv_lines': 'neonatal_ua_uv_lines.html',
    'neurology_increased_icp': 'neurology_increased_icp.html',
    'neurology_status_epilepticus': 'neurology_status_epilepticus.html',
    'nicu_section': 'nicu_section.html',
    'nsaids': 'nsaids.html',
    'numeric_rating_scale': 'numeric_rating_scale.html',
    'opioid_withdrawal': 'opioid_withdrawal.html',
    'opioids': 'opioids.html',
    'pain_evaluation': 'pain_evaluation.html',
    'pca_getting_pca_data': 'pca_getting_pca_data.html',
    'pca_interrogation': 'pca_interrogation.html',
    'pca_pearls': 'pca_pearls.html',
    'phonebook_child_life_misc_dietary': 'phonebook_child_life_misc_dietary.html',
    'phonebook_cisco_phones_nursing': 'phonebook_cisco_phones_nursing.html',
    'phonebook_continuity_clinics': 'phonebook_continuity_clinics.html',
    'phonebook_general_chiefs_admin': 'phonebook_general_chiefs_admin.html',
    'phonebook_hospital_locations': 'phonebook_hospital_locations.html',
    'phonebook_labs_consults': 'phonebook_labs_consults.html',
    'phonebook_miscellaneous': 'phonebook_miscellaneous.html',
    'phonebook_outside_hospitals': 'phonebook_outside_hospitals.html',
    'phonebook_peds_fellows': 'phonebook_peds_fellows.html',
    'phonebook_pharmacy': 'phonebook_pharmacy.html',
    'phonebook_radiology': 'phonebook_radiology.html',
    'phonebook_section': 'phonebook_section.html',
    'phonebook_social_services': 'phonebook_social_services.html',
    'phonebook_subspecialty_clinics': 'phonebook_subspecialty_clinics.html',
    'pruritis_treatment': 'pruritis_treatment.html',
    'r_flacc_score': 'r_flacc_score.html',
    'respiratory_depression_treatment': 'respiratory_depression_treatment.html',
    'routine_care_post_op_cardiac': 'routine_care_post_op_cardiac.html',
    'sedation_score': 'sedation_score.html',
    'sma': 'sma.html',
    'specialty_by_topic_section': 'specialty_by_topic_section.html',
    'suggested_sedation_cardiac': 'suggested_sedation_cardiac.html',
    'temporary_pacemaker': 'temporary_pacemaker.html',
    'urinary_retention': 'urinary_retention.html',
    'verbal_pain_scale': 'verbal_pain_scale.html',
    'visual_analog_scale': 'visual_analog_scale.html',
    'withdrawal': 'withdrawal.html',
}

export default PagesFilenames;